<wsdl:definitions>
    <wsdl:type>
        <!-- Here in this section we define all the datatypes we need for the exchange info for this particular webservice   -->
        <xsd:import namespace="http://www.matenick.com/userProfile/schema/UserProfile.xsd" schemaLocation="UserProfile.xsd"/>
        <xsd:element name="GetUserProfile">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="userName" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        <xsd:element name="GetUserProfileResponse">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="UserProfile" type="upSchema:UserProfile"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
    </wsdl:type>
    <!-- Once we define the type, we use these types in the second Section known as Messages -->
    <wsdl:message name="GetUserProfileRequest">
        <!-- Messages are Analogus to Paramethers and Return types in java -->
        <wsdl:part name="params" element="tns:GetUserProfile"/>
    </wsdl:message>
    <wsdl:message name="GetUserProfileResponse">
        <wsdl:part name="result" element="tns:GetUserRespinse"/>
    </wsdl:message>
    
    <wsdl:portType name="UserProfilePortType">
        <!-- It is the container of all the operations my webservice is providing -->
        <wsdl:operation name="GetUserProfile">  <!-- These operations are analogus to methods in java-->
            <wsdl:input message="tns:GetUserProfileRequest"/>
            <wsdl:output message="tns:GetUserProfileResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <!-- How the consumer can use this web Service-->
    <wsdl:binding name="UserProfileBinding" type="tns:UserProfilePortType"> 
    <!-- The Link Between the Physical Section and Abstract section is maintained by Port type above this line-->
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetUserPorfile">
            <soap:operation soapAction="urn:GetUserPorfile"/>
            <wsdl:input>
                <soap:body use="literal"/>  <!-- It is recommended-->
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="UserProfileService">
        <wsdl:port binding="tns:UserProfileBinding" name="UserProfilePort">
            <!-- This URL is Replaced by Apache CXF in real time as a webservice endpoint -->
            <soap:address location="http://localhost/services/UserProfileService"/>

        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>


 